### ISSUE TITLE
Notify calls private telegram endpoint

### ISSUE THREAD

**Issue by Otto-AA** [Troublor/erebus-redgiant#2]
The notify option calls a seemingly private API endpoint. You may want to remove this from the source code and change the endpoint (or add some kind of authentication). I didn't test if it still works though.

https://github.com/Troublor/erebus-redgiant/blob/87477722ba15abe870e59542cde2aabcc16c7363/cmd/collect.go#L145-L166

**Comment by Troublor** [comment]
Thanks for your advice. I will delete this part.
