### ISSUE TITLE
`profitTx` is missing in dataset.json

### ISSUE THREAD

**Issue by Otto-AA** [Troublor/erebus-redgiant#5]
In https://github.com/Troublor/erebus-redgiant/blob/main/benchmark.md it describes that $T_a^p$ is saved as `profitTx`. While I've found this in the rq1-3_search.json file, the dataset.json file does not include it.

To verify this, you can run `grep -i profitTx dataset.json | wc -l` on the extracted json file, returning `0`.

Could you add this property to the dataset and reupload it?

**Comment by Troublor** [comment]
Thanks for pointing out the issue. There must be some bug in my previous script to export data from mongodb. 
I re-export again and you can download the new one here: 
https://drive.google.com/file/d/1Cjj0tArosCuBsZp9NrF7A3HvTOmbEnBb/view?usp=sharing

(The benchmark.md has been updated accordingly)

**Comment by Otto-AA** [comment]
Thank you for the fast update, looks good now!
